### ISSUE TITLE
Add void waitForTermination() { thread_.waitForTermination() }; to ThreadedNode..

### ISSUE THREAD

**Issue by cbecker** [jpilet/mediagraph#9]
Add to ThreadedNode, respective test and check on test_package:
```
void waitForTermination() { thread_.waitForTermination() };
```

**Comment by cbecker** [comment]
@jpilet what about having something like `graph.join()` to wait for all possible threads?
(or maybe even `graph.join(timeout)`)

**Comment by jpilet** [comment]
I would say there's no need to put join() in the Graph class.
We can implement it with a graph visitor. That would be:
joinAllThreadedNodes(graph, timeout);
